language: ruby
rvm:
    - 2.1.0
    - 2.0.0
    - 1.9.3
    - ruby-head
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: jruby-head
    - rvm: rbx-2
  allow_failures:
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
    - rvm: rbx-2
  fast_finish: true
branches:
    only: master


